ticket:3542 - Make lk buildable with GCC 4.9.1
Fix:
| In file included from lib/openssl/crypto/sha/sha_locl.h:117:0,
|                  from lib/openssl/crypto/sha/sha1dgst.c:71:
| lib/openssl/crypto/md32_common.h: In function 'SHA1_Final':
| lib/openssl/crypto/md32_common.h:234:45: error: right-hand operand of
comma expression has no effect [-Werror=unused-value]
|      *((c)++)=(unsigned char)(((l)    )&0xff), \
|                                              ^
| lib/openssl/crypto/sha/sha_locl.h:72:14: note: in expansion of macro
'HOST_l2c'
|   ll=(c)->h0; HOST_l2c(ll,(s)); \

Change-Id: I73d31939cd59ba6908008317dfbe16d35154605f